### PR TITLE
Add object to CSV methods, other improvements

### PR DESCRIPTION
**Pull request by veryprofessionaldodo**
| - | - |
| --- | --- |
| Issue | Related to [ripe-pulse/#302](https://github.com/ripe-tech/ripe-pulse/issues/302) |
| Dependencies | https://github.com/ripe-tech/ripe-commons-js/pull/33 |
| Decisions | There was no way to convert an object to CSV, and the previous structure was rather inflexible in how it could be used. This improved flexibility, reliability with a new way to convert to string any value, while giving the new adding the capability to covert objects and lists of objects to a CSV format, with possibly custom delimiters. |

### CODE REVIEW

**Review by joao-conde — APPROVED** [review]

**Review by NFSS10 — APPROVED** [review]

**Comment by joamag** [comment]
@veryprofessionaldodo which of these methods are new and have been developed?

**Comment by veryprofessionaldodo** [comment]
@joamag This builds on top of the of the [other PR](https://github.com/ripe-tech/ripe-commons-js/pull/33), so only after that is merged will the differences be clearer. In summary, the `buildCsv` and `toString` functions were removed, in favour of `arrayListToCsv`, `arrayToCsv`, `objectListToCsv`, `objectToCsv` and `parseStringDelimiter`, which replaces the `toString` function, being more reliable when dealing with objects that contain the delimiter inside.

**Comment by joamag** [comment]
Just added equivalent functionality to the main branch inspired by many of the changes in this PR. Closing it now as redundant. Good job

**Comment by veryprofessionaldodo** [comment]
@joamag No problem. However, in the future, I would like to know more about why sometimes PRs like this aren't merged. It helps me to know how to improve for next time, without having to guess what was wrong with my approach.

**Pull request closed without merging**
